/**
 * 以下から問題を抜粋
 * http://xn--pdf-j54ei15ebha115e5idf35iogd.com/pdf_201607/201607_chobeginer.pdf
 */
module.exports = [
    [
        [1, 7, 4, null, null, 8, 6, null, 5],
        [6, 3, null, null, null, null, 2, null, null],
        [null, 8, null, 1, 9, null, 7, 3, null],
        [null, null, null, 8, null, null, null, null, null],
        [5, null, null, null, 1, null, 8, null, null],
        [null, 6, 3, null, null, 9, 1, 4, null],
        [null, null, 1, 3, 8, null, null, null, 9],
        [null, null, 8, null, null, null, 4, 2, null],
        [null, null, null, null, 5, null, null, 1, null],
    ],
    [
        [6, null, 3, 5, null, null, null, null, 7],
        [null, null, null, 7, null, null, null, 9, 8],
        [7, null, null, null, null, null, null, null, null],
        [null, null, 1, null, null, null, 8, 2, null],
        [2, 4, null, null, null, 1, 7, null, null],
        [8, 5, null, null, 2, null, null, null, 6],
        [null, null, null, 6, null, 5, null, 3, null],
        [1, 8, null, 4, null, 2, 5, null, null],
        [5, null, null, null, null, 9, null, null, null],
    ],
    [
        [null, null, null, 1, 9, null, null, null, null],
        [4, 9, null, 7, null, null, null, null, 1],
        [8, 1, 3, null, null, null, null, 9, null],
        [6, 2, 7, 4, 8, null, null, null, null],
        [9, null, null, 2, null, null, 8, null, null],
        [null, null, null, null, 6, null, null, null, 5],
        [null, null, null, null, 2, 3, null, null, null],
        [3, 5, 1, null, 4, null, null, 2, 6],
        [null, 8, null, 9, null, null, 5, null, null],
    ],
    [
        [4, null, null, null, 8, null, 1, 6, 7],
        [null, null, null, 6, null, 3, null, 8, 2],
        [null, 2, 8, null, null, null, 9, 5, 3],
        [1, null, null, null, null, null, 8, 7, null],
        [null, null, null, null, null, null, null, null, 1],
        [null, 7, null, null, 2, 4, 5, 3, null],
        [null, null, 5, 3, 6, 1, null, 4, null],
        [3, null, null, null, null, null, 6, null, 8],
        [null, 9, null, 2, null, 8, null, 1, null],
    ],
    [
        [1, null, 4, 8, null, null, null, null, 5],
        [3, null, null, null, null, null, null, null, 9],
        [null, 8, null, null, null, null, 6, null, null],
        [4, null, 6, 7, 9, null, 8, 5, null],
        [5, 2, null, 4, 6, 8, null, null, null],
        [7, 9, 8, 5, null, 3, null, null, null],
        [null, null, 1, 9, 4, 5, 2, null, 8],
        [null, 7, null, null, 8, null, null, 4, null],
        [null, null, null, 3, null, 1, null, null, null],
    ],
];
